version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: govseva
      MYSQL_USER: govseva
      MYSQL_PASSWORD: govpass
    ports: ["3306:3306"]
  app:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://govseva:govpass@db:3306/govseva
      FLASK_SECRET_KEY: change-me
    ports: ["5000:5000"]
    depends_on: [db]
