openapi: 3.0.0
info:
  title: GovSeva API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login
      requestBody:
        required: true
      responses:
        '200':
          description: Logged in
  /register:
    post:
      summary: Register
      requestBody:
        required: true
      responses:
        '200':
          description: Registered
  /ticket/new:
    post:
      summary: Create new ticket
      responses:
        '302':
          description: Redirect to index on success
  /status/{ticket_id}:
    post:
      summary: Update ticket status
      parameters:
        - in: path
          name: ticket_id
          required: true
          schema: { type: integer }
      responses:
        '302':
          description: Redirect to index on success
